### ISSUE TITLE
ローカル環境で http://localhost:3000/ にアクセスするとエラー

### ISSUE THREAD

**Issue by shu0115** [FiNCDeveloper/shortener#20]
### スクリーンショット

![screencapture-localhost-3000-1459823659910](https://cloud.githubusercontent.com/assets/758374/14269755/7df8e396-fb22-11e5-8e97-337881dd5115.png)

### エラーログ

```
Processing by LocationsController#index as HTML
Completed 500 Internal Server Error in 25ms (ActiveRecord: 0.0ms)

NoMethodError - undefined method `split' for nil:NilClass:
  app/services/iptables_service.rb:3:in `initialize'
  app/controllers/locations_controller.rb:57:in `check_iptables'
  action_args (2.0.0) lib/action_args/params_handler.rb:7:in `send_with_method_parameters_from_params'
  action_args (2.0.0) lib/action_args/callbacks.rb:15:in `block in make_lambda'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:150:in `block (2 levels) in halting_and_conditional'
  actionpack (5.0.0.beta3) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:454:in `block in call'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:454:in `call'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0.beta3) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.0.0.beta3) lib/action_controller/metal/rescue.rb:27:in `process_action'
  actionpack (5.0.0.beta3) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (5.0.0.beta3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.0.beta3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.0.beta3) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (5.0.0.beta3) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (5.0.0.beta3) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  activerecord (5.0.0.beta3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (5.0.0.beta3) lib/abstract_controller/base.rb:128:in `process'
  actionview (5.0.0.beta3) lib/action_view/rendering.rb:30:in `process'
  actionpack (5.0.0.beta3) lib/action_controller/metal.rb:190:in `dispatch'
  actionpack (5.0.0.beta3) lib/action_controller/metal.rb:262:in `dispatch'
  actionpack (5.0.0.beta3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  actionpack (5.0.0.beta3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
  actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:39:in `block in serve'
  actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:26:in `serve'
  actionpack (5.0.0.beta3) lib/action_dispatch/routing/route_set.rb:724:in `call'
  bullet (5.0.0) lib/bullet/rack.rb:10:in `call'
  actionview (5.0.0.beta3) lib/action_view/digestor.rb:12:in `call'
  rack (2.0.0.alpha) lib/rack/etag.rb:25:in `call'
  rack (2.0.0.alpha) lib/rack/conditional_get.rb:25:in `call'
  rack (2.0.0.alpha) lib/rack/head.rb:12:in `call'
  rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:220:in `context'
  rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:214:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  activerecord (5.0.0.beta3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (5.0.0.beta3) lib/active_record/connection_adapters/abstract/connection_pool.rb:963:in `call'
  activerecord (5.0.0.beta3) lib/active_record/migration.rb:558:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/reloader.rb:71:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  web-console (3.1.1) lib/web_console/middleware.rb:131:in `call_app'
  web-console (3.1.1) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.1.1) lib/web_console/middleware.rb:18:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.0.0.beta3) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.0.0.beta3) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:70:in `block in tagged'
  activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:70:in `tagged'
  railties (5.0.0.beta3) lib/rails/rack/logger.rb:24:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.0.alpha) lib/rack/method_override.rb:22:in `call'
  rack (2.0.0.alpha) lib/rack/runtime.rb:22:in `call'
  activesupport (5.0.0.beta3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/load_interlock.rb:13:in `call'
  actionpack (5.0.0.beta3) lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.0.alpha) lib/rack/sendfile.rb:111:in `call'
  railties (5.0.0.beta3) lib/rails/engine.rb:522:in `call'
  puma (3.1.0) lib/puma/configuration.rb:227:in `call'
  puma (3.1.0) lib/puma/server.rb:561:in `handle_request'
  puma (3.1.0) lib/puma/server.rb:406:in `process_client'
  puma (3.1.0) lib/puma/server.rb:271:in `block in run'
  puma (3.1.0) lib/puma/thread_pool.rb:111:in `block in spawn_thread'
```

**Comment by shu0115** [comment]
[IPアドレスでアクセスを制限する by chrisfinc · Pull Request #15 · FiNCDeveloper/shortener](https://github.com/FiNCDeveloper/shortener/pull/15/files)

@chrisfinc ↑これ実装した時、ローカルで動作確認ってした？

↓とりあえず対処入れちゃったけど
https://github.com/FiNCDeveloper/shortener/pull/21/files#diff-54b4e4f2b562d74dad3af78e66e74e4fR71

↓ここで引数の`ip_addresses`が`nil`のケースも想定しておいた方が良かったかもね。
https://github.com/FiNCDeveloper/shortener/pull/15/files#diff-a50e96845612951e8aeb95e3794a214bR3

`IptablesService.new(ip_addresses)`←こっちのメソッド呼ぶ側で`ip_addresses`のnil判定とかしても良いけど。
